### PR TITLE
Composition without epsilon self-loops

### LINKED ISSUE #609: UB causing segfaults in `nft::is_in_lang()`
There is a UB in `nft::is_in_lang()` that causes segfaults, but appears very rarely. The bug can be seen in the following test: https://github.com/VeriFIT/mata/pull/601#discussion_r2661568963.

Might be related to another UB appearing in `mata::nft::union_nondet()`:

```text
### mata::nft::union_nondet() minimal
failing minimal scenario
mata/tests/nft/nft.cc:2730
...............................................................................
mata/tests/nft/nft.cc:2730: FAILED:
{Unknown expression after the reported line}
due to a fatal error condition:
SIGSEGV - Segmentation violation signal
```

Both UBs need to be fixed.

### PR DESCRIPTION
**Pull request by koniksedy**
This PR introduces:
- a new, more efficient way of computing the composition of two NFTs that does not use jump transitions,
- a third `JumpMode` – `JumpMode::NoJump`,
- an auxiliary function for creating a transition of length N, 
- a fix for a bug in `Nft::unify_nondet_with` that did not update levels correctly, 
- adds a dispatch function for composition that distinguishes between two composition modes (`General` and `FastNoJump`), and
- modifies calls to `compose` and `apply` within `replace_reluctant` and `noodlify` by passing `JumpMode::NoJump` as the `jump_mode`, because I believe that in these places the NFTs never contain jump transitions.

The new implementation of the composition works only on NFTs without jump transitions (with JumpMode::NoJump). Therefore, it does not need to unwind transitions or create local copies, unlike the general version of the composition. It also does not construct the “waiting loops” on zero-level states, which in the general version are used when the NFT cannot synchronize on epsilon and therefore has to wait.

### CODE REVIEW

**Comment by Adda0** [comment]
@koniksedy Hey, what is the status of this PR? We might potentially want to base our next research on what “shapes” of transducers are created by this composition approach. Are there any missing features left to implement in this PR?

**Comment by koniksedy** [comment]
There’s still a bug that needs to be fixed before it can be used. I haven’t had much time to work on it (I was also on vacation), but I can take a look at it. Hopefully, it should be done by the middle of next week.

But if you need a somewhat working version, you can use the commit 1282c59a93563edd71d8c6af9e323940688df875.

File: include/mata/nft/nft.hh [hunk 1]
```diff
@@ -340,6 +340,45 @@ public:
...
+     * @brief Add a single NFT transition with a length @p length from a source state @p source
+     * to a newly created target state, creating as many inner states as needed for the transition
+     * @p length and the jump mode.
+     *
+     * @param source The source state where the transition begins. @p source must already exist.
+     * @param symbol The symbol used for the transition.
+     * @param length The length of the transition.
+     * @param jump_mode Specifies the semantic of jump transitions (transitions with a length greater than 1).
+     */
+    State add_transition_with_lenght(State source, Symbol symbol, size_t length, JumpMode jump_mode = JumpMode::RepeatSymbol);
```
Comment (Adda0) [inline include/mata/nft/nft.hh]:
```suggestion
    State add_transition_with_length(State source, Symbol symbol, size_t length, JumpMode jump_mode = JumpMode::RepeatSymbol);
```
Fix typo

**Comment by jurajsic** [comment]
Current results for Z3-Noodler:
```
Benchmark transducer_plus
# of formulae: 91
--------------------------------------------------
tool                                ✅    ❌    time    avg    med     std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  ----  ----  ------  -----  -----  ------  -----  -------  ---------  ----  --------  -------
z3-noodler-b9a6f44-a89bddc          43    48  316.44   7.36   0.31   15.35     39        4          0    40         8        0
z3-noodler-b9a6f44-ead2f90          44    47  431.10   9.80   0.31   21.63     40        4          0    36        11        0
z3-noodler-model-b9a6f44-a89bddc    42    49  291.56   6.94   0.43   15.51     38        4          0    40         9        0
z3-noodler-model-b9a6f44-ead2f90    44    47  435.24   9.89   0.49   21.31     40        4          0    37        10        0
--------------------------------------------------
```
newplot
newplot

There seems to be some formulae where there is degradation, but it is probably coming from Z3 randomness.

I called composition and apply with the default arguments, I assume it will automatically select the correct (no) jump mode?

**Review by jurajsic — APPROVED** [review]

**Comment by koniksedy** [comment]
> I called composition and apply with the default arguments, I assume it will automatically select the correct (no) jump mode?

If they are called from `replace_reluctant` or `noodlify`, then yes. Otherwise, the no jump mode is not set and a slow composition is used.
PS: There is no `apply` call in those functions.

**Comment by jurajsic** [comment]
> > I called composition and apply with the default arguments, I assume it will automatically select the correct (no) jump mode?
> 
> If they are called from `replace_reluctant` or `noodlify`, then yes. Otherwise, the no jump mode is not set and a slow composition is used. PS: There is no `apply` call in those functions.

I meant inside Z3-Noodler, not in mata. We use `apply` there (and also compose I think). So if we do not set the jump mode argument, it can create jumps?

**Comment by jurajsic** [comment]
I just read properly what you said. What should I call it with if I want to use the fast composition then? `mata::nft::JumpMode::NoJump`?

**Comment by koniksedy** [comment]
Yes. Then it will automatically select the fast composition. But it is your responsibility to ensure that the provided transducers have no jumps (epsilon jumps are OK).

Also, there needs to be exactly one synchronization level at each transducer (LHS and RHS). If there are more synchronization levels (e.g., 1 and 3 on the LHS and 2 and 5 on the RHS), then the slower, more general composition is also selected.

**Comment by jurajsic** [comment]
There seems to be some problem with the new composition. When I take this automaton:
```
@NFT-explicit
%Alphabet-auto
%Initial q0 q2 q3
%Final q1
%Levels q0:0 q1:0 q2:0 q3:0
%LevelsNum 2
q0 50 q1
q1 50 q1
q1 51 q1
q1 52 q1
q2 51 q1
q3 52 q1
```
graphviz

And compose it with this NFT (using `mata::nft::compose(nfa, nft, 0, 0, true, mata::nft::JumpMode::NoJump)`:
```
@NFT-explicit
%Alphabet-auto
%Initial q0
%Final q0
%Levels q0:0 q1:1 q2:1 q3:0 q4:1 q5:0 q6:1 q7:0 q8:1 q9:1 q10:1 q11:1
%LevelsNum 2
q0 48 q1
q0 49 q2
q0 50 q4
q0 51 q8
q0 52 q10
q0 196608 q11
q1 48 q0
q2 49 q0
q3 4294967295 q6
q4 48 q3
q5 4294967295 q2
q6 49 q5
q7 4294967295 q9
q8 48 q7
q9 48 q5
q10 49 q3
q11 196608 q0
```
graphviz(1)

I get this:
```
@NFT-explicit
%Alphabet-auto
%Initial q0 q1 q2
%Final q12
%Levels q0:0 q1:0 q2:0 q3:1 q4:1 q5:1 q6:0 q7:0 q8:1 q9:0 q10:1 q11:1 q12:0
%LevelsNum 2
q0 50 q3
q0 51 q3
q0 52 q3
q1 50 q4
q1 51 q4
q1 52 q4
q2 50 q5
q2 51 q5
q2 52 q5
q3 48 q6
q4 48 q7
q5 49 q6
q6 4294967295 q8
q7 4294967295 q10
q8 49 q9
q9 4294967295 q11
q10 48 q9
q11 49 q12
q12 50 q3
q12 50 q4
q12 50 q5
q12 51 q3
q12 51 q4
q12 51 q5
q12 52 q3
q12 52 q4
q12 52 q5
```
graphviz(2)

There are too many transitions coming from the initial states, for example the symbol (52,48) should not be allowed as the first symbol of any accepted word.

The previous composition (run as `mata::nft::compose(nfa, nft, 0, 0, true, mata::nft::JumpMode::RepeatSymbol)` returns (seemingly) correct result:
```
@NFT-explicit
%Alphabet-auto
%Initial q0 q1 q2
%Final q8
%Levels q0:0 q1:0 q2:0 q3:1 q4:0 q5:1 q6:0 q7:1 q8:0 q9:1 q10:1 q11:0 q12:1 q13:1 q14:1 q15:1
%LevelsNum 2
q0 50 q15
q1 51 q14
q2 52 q3
q3 49 q4
q4 4294967295 q5
q5 49 q6
q6 4294967295 q7
q7 49 q8
q8 50 q13
q8 51 q10
q8 52 q9
q9 49 q4
q10 48 q11
q11 4294967295 q12
q12 48 q6
q13 48 q4
q14 48 q11
q15 48 q4
```
graphviz(3)

File: src/nft/composition.cc [hunk 2]
```diff
@@ -2,14 +2,1031 @@
...
+        case CompositionMode::FastNoJump:
+            if (jump_mode != JumpMode::NoJump) {
+                throw std::invalid_argument("FastNoJump composition mode only supports NoJump jump mode.");
+            }
+            if (lhs_sync_levels.size() != 1 || rhs_sync_levels.size() != 1) {
+                throw std::invalid_argument("FastNoJump composition mode only supports a single synchronization level per NFT.");
+            }
+            return algorithms::compose_fast_no_jump(lhs, rhs, lhs_sync_levels.front(), rhs_sync_levels.front(), project_out_sync_levels);
+        case CompositionMode::Auto:
+            if (jump_mode == JumpMode::NoJump && lhs_sync_levels.size() == 1) {
```
Comment (jurajsic) [inline src/nft/composition.cc:220]: Should there also be check for `rhs_sync_levels.size() == 1`? In the previous case (`CompositionMode::FastNoJump`) there is a check for bot `lhs` and `rhs`.

Comment (koniksedy) [reply src/nft/composition.cc:220]: I see the confusion this can cause.

The previous if statement `lhs_sync_levels.size() != 1 || rhs_sync_levels.size() != 1` is there to throw an early exception, since `FastNoJump` can only be used when the number of sync levels is exactly 1. It does not check whether the number of sync levels matches between lhs and rhs (that case would be an error and is handled by an assert in the composition).

The if statement `jump_mode == JumpMode::NoJump && lhs_sync_levels.size() == 1`
implicitly expects `rhs_sync_levels` to also have size 1, just like `lhs_sync_levels`. It could explicitly check this, but I left that validation to the composition assert.

We can either:
- add an explicit check and throw a "number of sync levels mismatch" error as in the case of the first if, or
- remove the condition `rhs_sync_levels.size() != 1` from the previous if statement.

PS: We should consider whether to replace the assert that checks `lhs_sync_levels` and `rhs_sync_levels` have the same size with an exception.

File: include/mata/nft/nft.hh [hunk 3]
```diff
@@ -913,45 +952,56 @@ Nft intersection(const Nft& lhs, const Nft& rhs,
 /**
  * @brief Composes two NFTs (lhs || rhs; read as "rhs after lhs").
  *
- * This function computes the composition of two NFTs, `lhs` and `rhs`, by aligning their synchronization levels.
- * Transitions between two synchronization levels are ordered as follows: first the transitions of `lhs`, then
- * the transitions of `rhs` followed by next synchronization level (if exists). By default, synchronization
- * levels are projected out from the resulting NFT.
- *
- * Vectors of synchronization levels have to be non-empty and of the same size.
- *
```
Comment (jurajsic) [inline include/mata/nft/nft.hh:922]: Why did you remove this?

**Comment by jurajsic** [comment]
> There seems to be some problem with the new composition. When I take this automaton:
> 
> ```
> @NFT-explicit
> %Alphabet-auto
> %Initial q0 q2 q3
> %Final q1
> %Levels q0:0 q1:0 q2:0 q3:0
> %LevelsNum 2
> q0 50 q1
> q1 50 q1
> q1 51 q1
> q1 52 q1
> q2 51 q1
> q3 52 q1
> ```
> 
> graphviz

You can ignore this problem, the first automaton had 2 levels instead of one, so there were jumps. That is why the no jump version did not work.

File: src/nft/composition.cc (hunk 2 above)
Comment (jurajsic) [reply src/nft/composition.cc:220]: I would remove `rhs_sync_levels.size() != 1` so it is not confusing. I would also add the check for the number of sync levels mismatch, either at the beginning of this general compose function, or at the beginning of the compose functions implementations.

**Comment by jurajsic** [comment]
Current results:
```
Benchmark transducer_plus
# of formulae: 91
--------------------------------------------------
tool                                ✅    ❌    time    avg    med     std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  ----  ----  ------  -----  -----  ------  -----  -------  ---------  ----  --------  -------
z3-noodler-e775a54-a89bddc          43    48  329.00   7.65   0.31   16.24     39        4          0    40         8        0
z3-noodler-39dd4ed-27bd0e5          44    47  446.27  10.14   0.33   22.33     40        4          0    36        11        0
```
image


The small differences stem from Z3' randomness I think, so we can ignore it.

File: include/mata/nft/nft.hh (hunk 3 above)
Comment (koniksedy) [reply include/mata/nft/nft.hh:922]: To be honest, I have no idea, and I agree that it should stay there.

Comment (jurajsic) [reply include/mata/nft/nft.hh:922]: I put it back (and completely rewrote it).

**Comment by jurajsic** [comment]
I think we can merge.

**Comment by Adda0** [comment]
Now it just needs rebasing onto devel... I feel like we should first squash those 70 commits, then try to rebase.

**Review by Adda0 — APPROVED** [review]

File: src/nft/composition.cc (hunk 2 above)
Comment (Adda0) [reply src/nft/composition.cc:220]: @jurajsic Do you want to act on this in a future PR?

Comment (jurajsic) [reply src/nft/composition.cc:220]: Probably not
