### PR TITLE
Fix counterexamples for inclusion

### LINKED ISSUE #440: Incorrect counterexample in `is_included_antichains`
When I call
https://github.com/VeriFIT/mata/blob/17ffaf6e2a90a506c21abe5075893b505947322b/include/mata/nfa/algorithms.hh#L77
with the following two automata:
```
@NFA-explicit
%Alphabet-auto
%Initial q0
%Final q10
q0 65 q1
q0 66 q1
q0 67 q1
q0 196608 q1
q1 65 q2
q1 66 q2
q1 67 q2
q1 196608 q2
q2 65 q2
q2 65 q3
q2 66 q2
q2 66 q4
q2 67 q2
q2 196608 q2
q3 67 q11
q4 66 q5
q5 66 q6
q6 65 q6
q6 65 q7
q6 66 q6
q6 67 q6
q6 196608 q6
q7 67 q8
q8 67 q9
q9 67 q10
q10 65 q10
q10 66 q10
q10 67 q10
q10 196608 q10
q11 67 q12
q12 67 q13
q13 65 q13
q13 66 q13
q13 66 q14
q13 67 q13
q13 196608 q13
q14 66 q15
q15 66 q16
q16 65 q10
q16 66 q10
q16 67 q10
q16 196608 q10
```
and
```
@NFA-explicit
%Alphabet-auto
%Initial q0 q7
%Final q6
q0 65 q1
q0 66 q1
q0 67 q1
q0 196608 q1
q1 65 q2
q1 66 q2
q1 67 q2
q1 196608 q2
q2 65 q2
q2 66 q2
q2 66 q3
q2 67 q2
q2 196608 q2
q3 66 q4
q4 66 q5
q5 66 q6
q6 65 q6
q6 66 q6
q6 67 q6
q6 196608 q6
q7 65 q8
q7 66 q8
q7 67 q8
q7 196608 q8
q8 65 q8
q8 66 q9
q8 67 q8
q8 196608 q8
q9 65 q9
q9 65 q10
q9 66 q9
q9 67 q9
q9 196608 q9
q10 67 q5
```
I get incorrect counterexample, a word `65, 66, 66, 66, 66, 65, 67, 67`.
It seems that it missed the last symbol `67`.

### PR DESCRIPTION
**Pull request by jurajsic**
This PR fixes counterexamples for antichain inclusion algorithm (both the word and path were incorrect) and for naive algorithm it fixes the path in the counterexamples.

### CODE REVIEW

**Comment by jurajsic** [comment]
It seems that there is significant slowdown while generating counterexamples, see verifit/z3-noodler#183

File: include/mata/nfa/nfa.hh [hunk 1]
```diff
@@ -206,8 +206,25 @@ public:
      */
     Nfa& trim(StateRenaming* state_renaming = nullptr);
 
+    /**
+     * @brief Returns vector ret where ret[q] is the length of the shortest path from any initial state to q
+     */
     std::vector<State> distances_from_initial() const;
```
Comment (vhavlena) [inline include/mata/nfa/nfa.hh:212]: It would be nice if we have some general BFS/DFS method parameterized by callbacks (in a similar fashion as for Tarjan). All these functions such as `distances_from_initial` or `distances_to_final` could be easily expressible by this and you wouldn't need to write BFS/DFS all over again.

**Review by vhavlena — APPROVED** [review]
Nice!

File: include/mata/nfa/nfa.hh [hunk 2]
```diff
@@ -206,8 +206,25 @@ public:
...
 
+    /**
+     * @brief Returns vector ret where ret[q] is the length of the shortest path from q to any final state
+     */
+    std::vector<State> distances_to_final() const;
+
+    /**
+     * @brief Get some shortest accepting run from state @p q
+     * 
+     * Assumes that @p q is a state of this automaton and that there is some accepting run from q
```
Comment (Adda0) [inline include/mata/nfa/nfa.hh]:
```suggestion
     * Assumes that @p q is a state of this automaton and that there is some accepting run from @p q
```
Add Doxygen command for uniform naming.

File: src/nfa/inclusion.cc [hunk 3]
```diff
@@ -160,20 +172,27 @@ bool mata::nfa::algorithms::is_included_antichains(
...
+                        cex->path.push_back(smaller_state);
                         ProdStateType trav = prod_state;
-                        while (paths[trav].first != trav)
+                        while (paths.at(trav).first != trav)
                         { // go back until initial state
-                            cex->word.push_back(paths[trav].second);
-                            trav = paths[trav].first;
+                            cex->word.push_back(paths.at(trav).second);
+                            cex->path.push_back(std::get<0>(paths.at(trav).first));
+                            trav = paths.at(trav).first;
```
Comment (Adda0) [inline src/nfa/inclusion.cc]: Maybe extract the repeated call to `paths.at(trav)` to omit repeated binary searching (`std::map` searches are expensive).

**Review by Adda0 — APPROVED** [review]
Seems to be working as expected.

File: src/nfa/inclusion.cc (hunk 3 above)
Comment (jurajsic) [reply src/nfa/inclusion.cc]: Done

Comment (Adda0) [reply src/nfa/inclusion.cc]: Looks good.

File: include/mata/nfa/nfa.hh (hunk 1 above)
Comment (Adda0) [reply include/mata/nfa/nfa.hh:212]: Created an issue from this:  #446.
