### PR TITLE
Fix an issue with bad allocation in post

### LINKED ISSUE #173: Bug in determinize()
The following test produces an assertion failure.

```cpp
        Nfa x{};
        x.initial.add(0);
        x.final.add(4);
        x.delta.add(0, 1, 3);
        x.delta.add(3, 1, 3);
        x.delta.add(3, 2, 3);
        x.delta.add(3, 0, 1);
        x.delta.add(1, 1, 1);
        x.delta.add(1, 2, 1);
        x.delta.add(1, 0, 2);
        x.delta.add(2, 0, 2);
        x.delta.add(2, 1, 2);
        x.delta.add(2, 2, 2);
        x.delta.add(2, 0, 4);
        OnTheFlyAlphabet alphabet{};
        auto complement_result{ determinize(x) };
```

### PR DESCRIPTION
**Pull request by kilohsakul**
Fix of the problem with delta[q] reallocating post and screwing everything.

### CODE REVIEW

**Comment by Adda0** [comment]
I confirm that the tests run successfully on Linux.

**Comment by tfiedor** [comment]
Is this fix of #173 ?

**Comment by Adda0** [comment]
Yes, this is a fix for issue #173. However, this implements a different approach that what we have agreed on in our meeting. If we are OK with this approach instead, this PR would resolve #174, indeed.

**Comment by tfiedor** [comment]
Linked with #173 then

File: include/mata/nfa.hh [hunk 1]
```diff
@@ -214,6 +214,9 @@ struct Post : private Util::OrdVector<Move> {
 	}
 };
 
+
+    static Post empty_post;
```
Comment (tfiedor) [inline include/mata/nfa.hh]: I suggest making this `const` (if syntactically/semantically possible), since someone might add something (accidentaly) to this `empty_post` and then we will return non-empty post everytime.

File: include/mata/nfa.hh [hunk 2]
```diff
@@ -247,7 +251,20 @@ public:
     size_t size() const;
 
 
-    Post & operator[] (State q)
+    //Post & operator[] (State q)
```
Comment (tfiedor) [inline include/mata/nfa.hh]: Is it worth keeping the code commented out?

**Review by tfiedor — APPROVED** [review]
I have no major issues, I would strongly recommend to protect the static variable with const.

**Comment by kilohsakul** [comment]
Now it should be done, no more modifications planned.

File: include/mata/nfa.hh (hunk 1 above)
Comment (kilohsakul) [reply include/mata/nfa.hh]: ok, now it is there

File: include/mata/nfa.hh (hunk 2 above)
Comment (kilohsakul) [reply include/mata/nfa.hh]: no, it was a working version, actually I don't know why the reviewers were assigned automatically

**Comment by kilohsakul** [comment]
What should actually be the name of that function "mutable_post" ?? 
Something shorter? Like only delta.mutable(q)? delta.modifiable(q)? delta.modifier(q), ... or whatever else?

File: include/mata/nfa.hh (hunk 2 above)
Comment (Adda0) [reply include/mata/nfa.hh]: I assigned them manually.

**Comment by Adda0** [comment]
I quite like `mutable_post`, actually. I am open to other suggestions, though.

We could work with something as `mut_ref` as “mutable reference”. `nfa.delta.mut_ref(q)` reads naturally to me and it warns us each time we use it that it is mutable and we have to be careful.

File: include/mata/nfa.hh [hunk 3]
```diff
@@ -214,6 +214,8 @@ struct Post : private Util::OrdVector<Move> {
 	}
 };
 
+//static Post empty_post;
+
```
Comment (Adda0) [inline include/mata/nfa.hh]: Remove the commented out code.

**Review by Adda0 — APPROVED** [review]
If we are fine with this approach, the implementation seems OK to me.

File: include/mata/synchronized-iterator.hh [hunk 4]
```diff
@@ -35,6 +35,11 @@ namespace Mata {
         *  The memory allocated internally for positions and ends is kept after reset, so it is advisable to use the same iterator for many iterations, as
         *  opposed to creating a new one for each iteration.
         */
+        template<typename Inner> class Iterable {
+            
+        };
```
Comment (jurajsic) [inline include/mata/synchronized-iterator.hh]: Why was this introduced here?

**Review by jurajsic — APPROVED** [review]
It looks fine, if we are sure that the current usages of `mutable_post` cannot fuck up anything, then we can merge.

**Comment by Adda0** [comment]
>  if we are sure that the current usages of mutable_post cannot fuck up anything

In theory, it should not. This PR only makes it more obvious that the underlying structure can be modified. Therefore, one will not use the mutable accessor when they do not want to modify the data structure. Otherwise, using the mutable accessor behaves exactly as it did until now.

**Comment by kilohsakul** [comment]
> Yes, this is a fix for issue #173. However, this implements a different approach that what we have agreed on in our meeting. If we are OK with this approach instead, this PR would resolve #174, indeed.

That's true, but this was really easy, and it looks ok. As I was saying at the meeting, I actually like it this more, but I thought it would be harder to do.

**Comment by Adda0** [comment]
> this was really easy, and it looks ok.

I wholeheartedly agree. I am not against this approach. And as far as I know, I am not aware of any cases where this would not solve our problems.

File: include/mata/synchronized-iterator.hh (hunk 4 above)
Comment (Adda0) [reply include/mata/synchronized-iterator.hh]: It will be removed.

File: include/mata/nfa.hh (hunk 3 above)
Comment (Adda0) [reply include/mata/nfa.hh]: Removed.
