### PR TITLE
Fix simulation

### LINKED ISSUE #427: Bug in noodlification, specifically in simulation reduction
There seems to be some problem with reduction of the intersection automaton during noodlification, see [this commit](https://github.com/VeriFIT/mata/commit/ea68dc044967a3bf2b497d13593d237aff0c273c) for an example where this shows up.
The intersected automaton with epsilons should be simple line `q0 -0-> q1 -0-> q2 -eps-> q3 -0-> q4 -0-> q5` but for some reason, after reduction ([line 382](https://github.com/VeriFIT/mata/blob/ea68dc044967a3bf2b497d13593d237aff0c273c/src/strings/nfa-noodlification.cc#L382)), it turns into `q0 -0-> q1 -0-> q2 -eps-> q3` with self-loop on `q3` and NO final states.
Maybe the problem is that we are reducing and putting it into the same variable?

### PR DESCRIPTION
**Pull request by jurajsic**
If automaton contains symbol 0 and also largest possible symbol (usually epsilon), then simulation computation could be wrong, as it used some extra transitions with symbol `max_used_symbol + 1`, which would overflow to 0.

### CODE REVIEW

File: src/nfa/operations.cc [hunk 1]
```diff
@@ -24,21 +24,36 @@ using StateBoolArray = std::vector<bool>; ///< Bool array for states in the auto
...
+            auto it = used_symbols.begin();
+            unused_symbol = *it + 1;
+            ++it;
+            const auto used_symbols_end = used_symbols.end();
+            while (it != used_symbols_end && unused_symbol == *it) {    
+                unused_symbol = *it + 1;
+                ++it;
+            }
+            if (unused_symbol == 0) { // sanity check to see if we did not use the full range of mata::Symbol
+                throw std::runtime_error("all symbols are used, we cannot compute simluation reduction");
```
Comment (Adda0) [inline src/nfa/operations.cc]:
```suggestion
                throw std::runtime_error("all symbols are used, we cannot compute simulation reduction");
```
style: Fix typo

**Review by Adda0 — APPROVED** [review]
LGTM. Good catch.
