### PR TITLE
Fix bug in concatenation

### LINKED ISSUE #112: Concatenation bug
I have the following code:
```
Mata::Nfa::Nfa aut1;
Mata::RE2Parser::create_nfa(&aut1, "a*");
Mata::Nfa::Nfa aut2;
Mata::RE2Parser::create_nfa(&aut2, "b*");
Mata::Nfa::Nfa aut3;
Mata::RE2Parser::create_nfa(&aut3, "a*b*");
Mata::Nfa::are_equivalent(Mata::Nfa::concatenate(aut1, aut2), aut3);
```
The equivalence check on the last line should be true, but it is not. It seems there is a problem in concatenation resulting in this case to the NFA accepting "(a|b)*".

### PR DESCRIPTION
**Pull request by Adda0**
This PR:
- fixes a bug in concatenation of NFAs accepting epsilon strings,
- fixes a bug in function removing epsilon symbols.

The current fix concatenates over epsilon transitions and removes epsilons if the concatenation should not use epsilon symbols. An optimized algorithm for concatenation, based on the previous one with fixed handling of NFAs accepting empty strings, is a potential future project if the concatenation proves to be a bottleneck.

Resolves #112.

### CODE REVIEW

File: src/nfa/nfa-concatenation.cc [hunk 1]
```diff
@@ -26,131 +26,50 @@ Nfa concatenate(const Nfa& lhs, const Nfa& rhs, bool use_epsilon,
...
+        rhs.initial.empty() || rhs.final.empty()) {
+        return Nfa{};
+    }
 
     const unsigned long lhs_states_num{lhs.delta.post_size() };
     const unsigned long rhs_states_num{rhs.delta.post_size() };
     Nfa result{}; // Concatenated automaton.
     StateToStateMap lhs_result_states_map_internal{}; // Map mapping rhs states to result states.
     StateToStateMap rhs_result_states_map_internal{}; // Map mapping rhs states to result states.
+    const bool lhs_accepts_empty_string{ is_in_lang(lhs, Run{{}, {}}) };
```
Comment (tfiedor) [inline src/nfa/nfa-concatenation.cc:45]: Why not just write `lhs_accepts_empty_string = is_in_lang(...)`?

**Review by tfiedor — APPROVED** [review]
Seems fine to me.

File: src/nfa/nfa-concatenation.cc (hunk 1 above)
Comment (Adda0) [reply src/nfa/nfa-concatenation.cc:45]: Copy initialization (`int var = ...`) is a C concept which is discouraged in modern C++. Uniform initialization has added benefits such as consistent structure across variables of most types or prohibiting narrowing conversions. For reference, see [further explanation](https://www.learncpp.com/cpp-tutorial/variable-assignment-and-initialization/) or look for the explanation in [C++ reference](https://en.cppreference.com/w/cpp/language/list_initialization):
> Otherwise (if T is not a class type), if the braced-init-list has only one element and either T is not a reference type or is a reference type whose referenced type is same as or is a base class of the type of the element, T is [direct-initialized](https://en.cppreference.com/w/cpp/language/direct_initialization) (in direct-list-initialization) or [copy-initialized](https://en.cppreference.com/w/cpp/language/copy_initialization) (in copy-list-initialization), except that narrowing conversions are not allowed.

Otherwise, it is the same.

**Review by vhavlena — COMMENTED** [review]
The code is fine. However, in the noodlification introduced in PR #129 we among others use concatenation over epsilon symbols given as a parameter, which is not supported here. So I suggest to first merge PR #129 and then extend the concatenation from here accordingly.

**Comment by martinhruska** [comment]
I have no issues with PR. I support procedure which Vojta proposed. We should first finish his PR and then modify this.

**Review by martinhruska — APPROVED** [review]

**Comment by martinhruska** [comment]
The PR #129. Could you please resolve the conflicts and modify this PR according to Vojta's suggestion @Adda0?

**Comment by Adda0** [comment]
Yes. I will update this PR to reflect the changes made in #129.

**Comment by Adda0** [comment]
The PR was rebased onto the current `devel` branch. I consider this PR to be ready to be merged.
