### PR TITLE
Fix warnings

### LINKED ISSUE #104: Resolve Mata compilation warnings
As time goes on and multiple Mata modules are implemented and modified (NFA, AFA, parser, etc.), the warnings returned by the compiler pile up. It becomes increasingly harder to search the build log for errors and meaningful warnings.

We should try to do some spring-cleaning a bit early in the year and fix as many warnings as possible. Write tests for unused functions, add `(void) param` in unimplemented functions and resolve other meaningful warnings so that it is easier for the developers to look through the build log and spot actually important warnings.

### PR DESCRIPTION
**Pull request by Adda0**
This PR fixes the code so no warnings are displayed. The purpose of this PR is to allow easier error fixing and producing more quality code. We will be able to actually see the new warnings and fix them as we introduce new features (or you better be able to run fast if you introduce new warnings in your PRs from now on). 

Some changes with default initialization simply replace an undefined behaviour we are being warned about by a defined, but maybe nonsensical value. That still has the same effect, however: the value should never be used in any case. More thorough fixes for these kinds of potential bugs may come in future.

I also modified a few places in external libraries in order to suppress warnings brought by including their header files. Note that I did not fix warnings introduced by external libraries during their compilation. I only fixed warnings generated by compilation of Mata library itself. 

The PR also refactors specifying compiler warnings flags in CMake which allow for a more unified and optionally more granular specification of said flags.

### CODE REVIEW

File: 3rdparty/simlib/src/explicit_lts_sim.cc [hunk 1]
```diff
@@ -150,6 +150,11 @@ struct Block
 		} while (states != this->states_);
 	}
 
+    Block(Block&) = default;
```
Comment (tfiedor) [inline 3rdparty/simlib/src/explicit_lts_sim.cc:153]: Unify indent with other lines

File: include/mata/closed-set.hh [hunk 2]
```diff
@@ -411,13 +414,13 @@ ClosedSet<T> ClosedSet<T>::complement() const {
...
-            ClosedSet preparingAntichain(downward_closed_set, get_min(), get_max());
-            for(int i = 0; i <= max_val_; ++i) {
+            ClosedSet preparingAntichain(ClosedSetType::downward_closed_set, get_min(), get_max());
+            for(int i = 0; i <= static_cast<int>(max_val_); ++i) {
                 if(!element.count(i)) {
                     continue;
                 }
                 Node candidates{};
-                for(int j = 0; j <= max_val_; ++j) {
+                for(int j = 0; j <= static_cast<int>(max_val_); ++j) {
```
Comment (tfiedor) [inline include/mata/closed-set.hh]: Is `static_cast<>` cheap operation? I think it should be extract from the loop, since this might be repeated in each iteration. (Yeah, compiler might optimize this, but...)

File: include/mata/number-predicate.hh [hunk 3]
```diff
@@ -100,35 +100,29 @@ public:
...
     }
 
-    NumberPredicate(std::vector <Number> list, bool track_elements = true)
-        : elements_are_exact(true), tracking_elements(track_elements), cardinality(0) {
-        add(list);
+    NumberPredicate() = default;
+    explicit NumberPredicate(const bool track_elements) : tracking_elements(track_elements) {}
+    NumberPredicate(std::initializer_list<Number> list, bool track_elements = true)
+        : tracking_elements(track_elements) {
+        for (const auto& q: list) { add(q); }
```
Comment (tfiedor) [inline include/mata/number-predicate.hh:109]: Why was this changed from `add()` to `for () {add()}`?

File: src/inter-aut.cc [hunk 4]
```diff
@@ -226,12 +226,13 @@ namespace {
                     opstack.pop_back();
                     break;
                 case Mata::FormulaNode::Type::OPERATOR:
-                    for (int j = opstack.size()-1; j >= 0; --j) {
-                        assert(!opstack[j].is_operand());
-                        if (opstack[j].is_leftpar())
+                    for (int j = static_cast<int>(opstack.size())-1; j >= 0; --j) {
```
Comment (tfiedor) [inline src/inter-aut.cc:231]: The `size()` and cast could be extracted.

File: src/nfa/nfa.cc [hunk 5]
```diff
@@ -1038,7 +1041,7 @@ Nfa Mata::Nfa::somewhat_simple_revert(const Nfa& aut) {
 
     //sorting the targets
     for (State q = 0, states_num = result.delta.num_of_states(); q < states_num; ++q) {
-        Post & post = result.delta.get_mutable_post(q);
+        //Post & post = result.delta.get_mutable_post(q);
```
Comment (tfiedor) [inline src/nfa/nfa.cc:1044]: Why was this commented out?

File: src/nfa/nfa.cc [hunk 6]
```diff
@@ -1183,8 +1186,10 @@ bool Mata::Nfa::is_prfx_in_lang(const Nfa& aut, const Run& run)
 Mata::Parser::ParsedSection Mata::Nfa::serialize(
         const Nfa&                aut,
         const SymbolToStringMap*  symbol_map,
-        const StateToStringMap*   state_map)
-{assert(false);}
+        const StateToStringMap*   state_map) {
+    (void)aut; (void)symbol_map; (void)state_map;
+    assert(false);
```
Comment (tfiedor) [inline src/nfa/nfa.cc]: I would suggest to write this as `assert(false && "failing assert due to ...")`

**Review by tfiedor — APPROVED** [review]
Seems fine

File: 3rdparty/cudd/include/mata/cudd/cuddObj.hh [hunk 7]
```diff
@@ -92,7 +92,11 @@ protected:
     DD(Capsule *cap, DdNode *ddNode);
     DD(Cudd const & manager, DdNode *ddNode);
     DD(const DD &from);
+    DD(DD&& from) = default;
     ~DD();
+
+    DD& operator=(const DD& other) = default;
+    DD& operator=(DD&& other) = default;
```
Comment (jurajsic) [inline 3rdparty/cudd/include/mata/cudd/cuddObj.hh]: Why did you add these?

**Review by jurajsic — APPROVED** [review]

File: 3rdparty/simlib/src/explicit_lts_sim.cc (hunk 1 above)
Comment (Adda0) [reply 3rdparty/simlib/src/explicit_lts_sim.cc:153]: It is indented correctly. The problem is that the code around is indented with tabs, which show as only two whitespaces in GitHub by default.

File: include/mata/closed-set.hh (hunk 2 above)
Comment (Adda0) [reply include/mata/closed-set.hh]: This only explicitly writes out what happens implicitly behind during compilation. The type conversion is executed regardless of whether you write it out explicitly or not.

Comment (Adda0) [reply include/mata/closed-set.hh]: Therefore, this change did not affect performance. But as you suggest, we can optimize the further by extracting the cast outside the for loop manually.

Comment (Adda0) [reply include/mata/closed-set.hh]: That is why we should listen to these warnings ;) Good catch.

File: include/mata/number-predicate.hh (hunk 3 above)
Comment (Adda0) [reply include/mata/number-predicate.hh:109]: The for loop was already there. I only rewrote the code into a one-liner.

File: src/inter-aut.cc (hunk 4 above)
Comment (Adda0) [reply src/inter-aut.cc:231]: Done.

Comment (Adda0) [reply src/inter-aut.cc:231]: As in, the size() is called only once during the variable definition. It is not called each iteration.

File: src/nfa/nfa.cc (hunk 5 above)
Comment (Adda0) [reply src/nfa/nfa.cc:1044]: It is an unused variable. There is an already commented out function call below using this variable. This variable should be commented out together with that.

File: src/nfa/nfa.cc (hunk 6 above)
Comment (Adda0) [reply src/nfa/nfa.cc]: It is better, of course. However, there are numerous example of such failing asserts throughout the Mata code where a proper explanation is missing. I will modify the asserts in `nfa.cc`, but I will keep the rest unmodified.

File: 3rdparty/simlib/src/explicit_lts_sim.cc (hunk 1 above)
Comment (tfiedor) [reply 3rdparty/simlib/src/explicit_lts_sim.cc:153]: I see, I strongly advise against using tabs.

File: include/mata/closed-set.hh (hunk 2 above)
Comment (tfiedor) [reply include/mata/closed-set.hh]: Fair enough. To be honest, I think it might have minimal impact (I'm integer type conversion should IMO be costless), it just stand out and extract might also make it more readable. Or maybe change the `i` to unsigned instead? Does it need to be singed?

File: src/nfa/nfa.cc (hunk 6 above)
Comment (tfiedor) [reply src/nfa/nfa.cc]: Yes, I don't know how you were conducting these refactoring. I personally do many by hands and would hence fix this regardless of the rest of the `assert(false)` :)

File: 3rdparty/cudd/include/mata/cudd/cuddObj.hh (hunk 7 above)
Comment (Adda0) [reply 3rdparty/cudd/include/mata/cudd/cuddObj.hh]: There were warnings about having to implicitly derive copy and move assignments and constructors, specifically the copy constructor and assignment. This forced the functions to be created explicitly, which silenced the warnings.

File: 3rdparty/simlib/src/explicit_lts_sim.cc (hunk 1 above)
Comment (Adda0) [reply 3rdparty/simlib/src/explicit_lts_sim.cc:153]: We do not use them and I change tabs to spaces if I encounter them if the PR is suitable for such changes. But this is simlib and I did not want to introduce a change that would rewrite the whole file for an external library.

File: include/mata/closed-set.hh (hunk 2 above)
Comment (Adda0) [reply include/mata/closed-set.hh]: I will make the `j` variable of generic type `T` (the type of `max_val_`). That will resolve the issue everywhere.

Comment (Adda0) [reply include/mata/closed-set.hh]: Thank you for the discussion. This was actually a great optimization because we have to convert the `int j` again later into the `T` type anyway.

**Comment by Adda0** [comment]
I addressed all the issues. I will merge the PR soon unless there are any objections.

File: include/mata/closed-set.hh (hunk 2 above)
Comment (tfiedor) [reply include/mata/closed-set.hh]: Accidental optimization :D

**Comment by Adda0** [comment]
I implemented a proper copy assignment operator to set reference counting in CUDD. It should now work as required.
